// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// PostLike is the predicate function for postlike builders.
type PostLike func(*sql.Selector)

// PostMedia is the predicate function for postmedia builders.
type PostMedia func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)

// SavedPost is the predicate function for savedpost builders.
type SavedPost func(*sql.Selector)
