package.folders = conf
app.name = coach-connect-api
app.secret =
app.behind.proxy = false
http.addr = 127.0.0.1
http.port = 9000
http.ssl = false
http.timeout.read = 15
http.timeout.write = 30
results.chunked = false
results.compressed = true

[dev]
mode.dev = true
app.secret = coach-connect-local-development-only
results.pretty = true
watch = true
watch.mode = eager
log.error.output = stderr
log.warn.output = stderr

[test]
mode.dev = false
app.secret = coach-connect-test-only
results.pretty = false
watch = false
log.error.output = stderr

[prod]
mode.dev = false
app.secret = ${APP_SECRET}
app.behind.proxy = true
results.pretty = false
watch = false
log.error.output = stderr
log.warn.output = stderr
