// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/postmedia"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/predicate"
)

// PostMediaDelete is the builder for deleting a PostMedia entity.
type PostMediaDelete struct {
	config
	hooks    []Hook
	mutation *PostMediaMutation
}

// Where appends a list predicates to the PostMediaDelete builder.
func (_d *PostMediaDelete) Where(ps ...predicate.PostMedia) *PostMediaDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PostMediaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PostMediaDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PostMediaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(postmedia.Table, sqlgraph.NewFieldSpec(postmedia.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PostMediaDeleteOne is the builder for deleting a single PostMedia entity.
type PostMediaDeleteOne struct {
	_d *PostMediaDelete
}

// Where appends a list predicates to the PostMediaDelete builder.
func (_d *PostMediaDeleteOne) Where(ps ...predicate.PostMedia) *PostMediaDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PostMediaDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{postmedia.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PostMediaDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
