// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/postmedia"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/predicate"
)

// PostMediaUpdate is the builder for updating PostMedia entities.
type PostMediaUpdate struct {
	config
	hooks    []Hook
	mutation *PostMediaMutation
}

// Where appends a list predicates to the PostMediaUpdate builder.
func (_u *PostMediaUpdate) Where(ps ...predicate.PostMedia) *PostMediaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPublicURL sets the "public_url" field.
func (_u *PostMediaUpdate) SetPublicURL(v string) *PostMediaUpdate {
	_u.mutation.SetPublicURL(v)
	return _u
}

// SetNillablePublicURL sets the "public_url" field if the given value is not nil.
func (_u *PostMediaUpdate) SetNillablePublicURL(v *string) *PostMediaUpdate {
	if v != nil {
		_u.SetPublicURL(*v)
	}
	return _u
}

// SetAltText sets the "alt_text" field.
func (_u *PostMediaUpdate) SetAltText(v string) *PostMediaUpdate {
	_u.mutation.SetAltText(v)
	return _u
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_u *PostMediaUpdate) SetNillableAltText(v *string) *PostMediaUpdate {
	if v != nil {
		_u.SetAltText(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *PostMediaUpdate) SetMimeType(v string) *PostMediaUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *PostMediaUpdate) SetNillableMimeType(v *string) *PostMediaUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *PostMediaUpdate) SetWidth(v int) *PostMediaUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *PostMediaUpdate) SetNillableWidth(v *int) *PostMediaUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *PostMediaUpdate) AddWidth(v int) *PostMediaUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *PostMediaUpdate) SetHeight(v int) *PostMediaUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *PostMediaUpdate) SetNillableHeight(v *int) *PostMediaUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *PostMediaUpdate) AddHeight(v int) *PostMediaUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// Mutation returns the PostMediaMutation object of the builder.
func (_u *PostMediaUpdate) Mutation() *PostMediaMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostMediaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostMediaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostMediaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostMediaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostMediaUpdate) check() error {
	if v, ok := _u.mutation.PublicURL(); ok {
		if err := postmedia.PublicURLValidator(v); err != nil {
			return &ValidationError{Name: "public_url", err: fmt.Errorf(`ent: validator failed for field "PostMedia.public_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AltText(); ok {
		if err := postmedia.AltTextValidator(v); err != nil {
			return &ValidationError{Name: "alt_text", err: fmt.Errorf(`ent: validator failed for field "PostMedia.alt_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := postmedia.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "PostMedia.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := postmedia.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "PostMedia.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := postmedia.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "PostMedia.height": %w`, err)}
		}
	}
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostMedia.post"`)
	}
	return nil
}

func (_u *PostMediaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(postmedia.Table, postmedia.Columns, sqlgraph.NewFieldSpec(postmedia.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicURL(); ok {
		_spec.SetField(postmedia.FieldPublicURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AltText(); ok {
		_spec.SetField(postmedia.FieldAltText, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(postmedia.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(postmedia.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(postmedia.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(postmedia.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(postmedia.FieldHeight, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postmedia.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostMediaUpdateOne is the builder for updating a single PostMedia entity.
type PostMediaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMediaMutation
}

// SetPublicURL sets the "public_url" field.
func (_u *PostMediaUpdateOne) SetPublicURL(v string) *PostMediaUpdateOne {
	_u.mutation.SetPublicURL(v)
	return _u
}

// SetNillablePublicURL sets the "public_url" field if the given value is not nil.
func (_u *PostMediaUpdateOne) SetNillablePublicURL(v *string) *PostMediaUpdateOne {
	if v != nil {
		_u.SetPublicURL(*v)
	}
	return _u
}

// SetAltText sets the "alt_text" field.
func (_u *PostMediaUpdateOne) SetAltText(v string) *PostMediaUpdateOne {
	_u.mutation.SetAltText(v)
	return _u
}

// SetNillableAltText sets the "alt_text" field if the given value is not nil.
func (_u *PostMediaUpdateOne) SetNillableAltText(v *string) *PostMediaUpdateOne {
	if v != nil {
		_u.SetAltText(*v)
	}
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *PostMediaUpdateOne) SetMimeType(v string) *PostMediaUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *PostMediaUpdateOne) SetNillableMimeType(v *string) *PostMediaUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *PostMediaUpdateOne) SetWidth(v int) *PostMediaUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *PostMediaUpdateOne) SetNillableWidth(v *int) *PostMediaUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *PostMediaUpdateOne) AddWidth(v int) *PostMediaUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *PostMediaUpdateOne) SetHeight(v int) *PostMediaUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *PostMediaUpdateOne) SetNillableHeight(v *int) *PostMediaUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *PostMediaUpdateOne) AddHeight(v int) *PostMediaUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// Mutation returns the PostMediaMutation object of the builder.
func (_u *PostMediaUpdateOne) Mutation() *PostMediaMutation {
	return _u.mutation
}

// Where appends a list predicates to the PostMediaUpdate builder.
func (_u *PostMediaUpdateOne) Where(ps ...predicate.PostMedia) *PostMediaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostMediaUpdateOne) Select(field string, fields ...string) *PostMediaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PostMedia entity.
func (_u *PostMediaUpdateOne) Save(ctx context.Context) (*PostMedia, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostMediaUpdateOne) SaveX(ctx context.Context) *PostMedia {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostMediaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostMediaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostMediaUpdateOne) check() error {
	if v, ok := _u.mutation.PublicURL(); ok {
		if err := postmedia.PublicURLValidator(v); err != nil {
			return &ValidationError{Name: "public_url", err: fmt.Errorf(`ent: validator failed for field "PostMedia.public_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AltText(); ok {
		if err := postmedia.AltTextValidator(v); err != nil {
			return &ValidationError{Name: "alt_text", err: fmt.Errorf(`ent: validator failed for field "PostMedia.alt_text": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := postmedia.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "PostMedia.mime_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := postmedia.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "PostMedia.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := postmedia.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "PostMedia.height": %w`, err)}
		}
	}
	if _u.mutation.PostCleared() && len(_u.mutation.PostIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PostMedia.post"`)
	}
	return nil
}

func (_u *PostMediaUpdateOne) sqlSave(ctx context.Context) (_node *PostMedia, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(postmedia.Table, postmedia.Columns, sqlgraph.NewFieldSpec(postmedia.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PostMedia.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, postmedia.FieldID)
		for _, f := range fields {
			if !postmedia.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != postmedia.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicURL(); ok {
		_spec.SetField(postmedia.FieldPublicURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AltText(); ok {
		_spec.SetField(postmedia.FieldAltText, field.TypeString, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(postmedia.FieldMimeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(postmedia.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(postmedia.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(postmedia.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(postmedia.FieldHeight, field.TypeInt, value)
	}
	_node = &PostMedia{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{postmedia.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
