// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/post"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/postmedia"
)

// PostMediaCreate is the builder for creating a PostMedia entity.
type PostMediaCreate struct {
	config
	mutation *PostMediaMutation
	hooks    []Hook
}

// SetPostID sets the "post_id" field.
func (_c *PostMediaCreate) SetPostID(v string) *PostMediaCreate {
	_c.mutation.SetPostID(v)
	return _c
}

// SetObjectKey sets the "object_key" field.
func (_c *PostMediaCreate) SetObjectKey(v string) *PostMediaCreate {
	_c.mutation.SetObjectKey(v)
	return _c
}

// SetPublicURL sets the "public_url" field.
func (_c *PostMediaCreate) SetPublicURL(v string) *PostMediaCreate {
	_c.mutation.SetPublicURL(v)
	return _c
}

// SetAltText sets the "alt_text" field.
func (_c *PostMediaCreate) SetAltText(v string) *PostMediaCreate {
	_c.mutation.SetAltText(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *PostMediaCreate) SetMimeType(v string) *PostMediaCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *PostMediaCreate) SetWidth(v int) *PostMediaCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetHeight sets the "height" field.
func (_c *PostMediaCreate) SetHeight(v int) *PostMediaCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PostMediaCreate) SetCreatedAt(v time.Time) *PostMediaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PostMediaCreate) SetID(v string) *PostMediaCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetPost sets the "post" edge to the Post entity.
func (_c *PostMediaCreate) SetPost(v *Post) *PostMediaCreate {
	return _c.SetPostID(v.ID)
}

// Mutation returns the PostMediaMutation object of the builder.
func (_c *PostMediaCreate) Mutation() *PostMediaMutation {
	return _c.mutation
}

// Save creates the PostMedia in the database.
func (_c *PostMediaCreate) Save(ctx context.Context) (*PostMedia, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostMediaCreate) SaveX(ctx context.Context) *PostMedia {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostMediaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostMediaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostMediaCreate) check() error {
	if _, ok := _c.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "PostMedia.post_id"`)}
	}
	if _, ok := _c.mutation.ObjectKey(); !ok {
		return &ValidationError{Name: "object_key", err: errors.New(`ent: missing required field "PostMedia.object_key"`)}
	}
	if v, ok := _c.mutation.ObjectKey(); ok {
		if err := postmedia.ObjectKeyValidator(v); err != nil {
			return &ValidationError{Name: "object_key", err: fmt.Errorf(`ent: validator failed for field "PostMedia.object_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublicURL(); !ok {
		return &ValidationError{Name: "public_url", err: errors.New(`ent: missing required field "PostMedia.public_url"`)}
	}
	if v, ok := _c.mutation.PublicURL(); ok {
		if err := postmedia.PublicURLValidator(v); err != nil {
			return &ValidationError{Name: "public_url", err: fmt.Errorf(`ent: validator failed for field "PostMedia.public_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AltText(); !ok {
		return &ValidationError{Name: "alt_text", err: errors.New(`ent: missing required field "PostMedia.alt_text"`)}
	}
	if v, ok := _c.mutation.AltText(); ok {
		if err := postmedia.AltTextValidator(v); err != nil {
			return &ValidationError{Name: "alt_text", err: fmt.Errorf(`ent: validator failed for field "PostMedia.alt_text": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MimeType(); !ok {
		return &ValidationError{Name: "mime_type", err: errors.New(`ent: missing required field "PostMedia.mime_type"`)}
	}
	if v, ok := _c.mutation.MimeType(); ok {
		if err := postmedia.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`ent: validator failed for field "PostMedia.mime_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "PostMedia.width"`)}
	}
	if v, ok := _c.mutation.Width(); ok {
		if err := postmedia.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "PostMedia.width": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "PostMedia.height"`)}
	}
	if v, ok := _c.mutation.Height(); ok {
		if err := postmedia.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "PostMedia.height": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PostMedia.created_at"`)}
	}
	if len(_c.mutation.PostIDs()) == 0 {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "PostMedia.post"`)}
	}
	return nil
}

func (_c *PostMediaCreate) sqlSave(ctx context.Context) (*PostMedia, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PostMedia.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PostMediaCreate) createSpec() (*PostMedia, *sqlgraph.CreateSpec) {
	var (
		_node = &PostMedia{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(postmedia.Table, sqlgraph.NewFieldSpec(postmedia.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ObjectKey(); ok {
		_spec.SetField(postmedia.FieldObjectKey, field.TypeString, value)
		_node.ObjectKey = value
	}
	if value, ok := _c.mutation.PublicURL(); ok {
		_spec.SetField(postmedia.FieldPublicURL, field.TypeString, value)
		_node.PublicURL = value
	}
	if value, ok := _c.mutation.AltText(); ok {
		_spec.SetField(postmedia.FieldAltText, field.TypeString, value)
		_node.AltText = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(postmedia.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(postmedia.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(postmedia.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(postmedia.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   postmedia.PostTable,
			Columns: []string{postmedia.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PostMediaCreateBulk is the builder for creating many PostMedia entities in bulk.
type PostMediaCreateBulk struct {
	config
	err      error
	builders []*PostMediaCreate
}

// Save creates the PostMedia entities in the database.
func (_c *PostMediaCreateBulk) Save(ctx context.Context) ([]*PostMedia, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PostMedia, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostMediaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostMediaCreateBulk) SaveX(ctx context.Context) []*PostMedia {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostMediaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostMediaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
