// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/comment"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/post"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/postmedia"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/profile"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescBody is the schema descriptor for body field.
	commentDescBody := commentFields[3].Descriptor()
	// comment.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	comment.BodyValidator = commentDescBody.Validators[0].(func(string) error)
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescBody is the schema descriptor for body field.
	postDescBody := postFields[2].Descriptor()
	// post.BodyValidator is a validator for the "body" field. It is called by the builders before save.
	post.BodyValidator = postDescBody.Validators[0].(func(string) error)
	postmediaFields := schema.PostMedia{}.Fields()
	_ = postmediaFields
	// postmediaDescObjectKey is the schema descriptor for object_key field.
	postmediaDescObjectKey := postmediaFields[2].Descriptor()
	// postmedia.ObjectKeyValidator is a validator for the "object_key" field. It is called by the builders before save.
	postmedia.ObjectKeyValidator = postmediaDescObjectKey.Validators[0].(func(string) error)
	// postmediaDescPublicURL is the schema descriptor for public_url field.
	postmediaDescPublicURL := postmediaFields[3].Descriptor()
	// postmedia.PublicURLValidator is a validator for the "public_url" field. It is called by the builders before save.
	postmedia.PublicURLValidator = postmediaDescPublicURL.Validators[0].(func(string) error)
	// postmediaDescAltText is the schema descriptor for alt_text field.
	postmediaDescAltText := postmediaFields[4].Descriptor()
	// postmedia.AltTextValidator is a validator for the "alt_text" field. It is called by the builders before save.
	postmedia.AltTextValidator = postmediaDescAltText.Validators[0].(func(string) error)
	// postmediaDescMimeType is the schema descriptor for mime_type field.
	postmediaDescMimeType := postmediaFields[5].Descriptor()
	// postmedia.MimeTypeValidator is a validator for the "mime_type" field. It is called by the builders before save.
	postmedia.MimeTypeValidator = postmediaDescMimeType.Validators[0].(func(string) error)
	// postmediaDescWidth is the schema descriptor for width field.
	postmediaDescWidth := postmediaFields[6].Descriptor()
	// postmedia.WidthValidator is a validator for the "width" field. It is called by the builders before save.
	postmedia.WidthValidator = postmediaDescWidth.Validators[0].(func(int) error)
	// postmediaDescHeight is the schema descriptor for height field.
	postmediaDescHeight := postmediaFields[7].Descriptor()
	// postmedia.HeightValidator is a validator for the "height" field. It is called by the builders before save.
	postmedia.HeightValidator = postmediaDescHeight.Validators[0].(func(int) error)
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescClerkSubject is the schema descriptor for clerk_subject field.
	profileDescClerkSubject := profileFields[1].Descriptor()
	// profile.ClerkSubjectValidator is a validator for the "clerk_subject" field. It is called by the builders before save.
	profile.ClerkSubjectValidator = profileDescClerkSubject.Validators[0].(func(string) error)
	// profileDescDisplayName is the schema descriptor for display_name field.
	profileDescDisplayName := profileFields[2].Descriptor()
	// profile.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	profile.DisplayNameValidator = profileDescDisplayName.Validators[0].(func(string) error)
	// profileDescAvatarURL is the schema descriptor for avatar_url field.
	profileDescAvatarURL := profileFields[3].Descriptor()
	// profile.AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	profile.AvatarURLValidator = profileDescAvatarURL.Validators[0].(func(string) error)
}
