// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/predicate"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/savedpost"
)

// SavedPostDelete is the builder for deleting a SavedPost entity.
type SavedPostDelete struct {
	config
	hooks    []Hook
	mutation *SavedPostMutation
}

// Where appends a list predicates to the SavedPostDelete builder.
func (_d *SavedPostDelete) Where(ps ...predicate.SavedPost) *SavedPostDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SavedPostDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SavedPostDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SavedPostDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(savedpost.Table, sqlgraph.NewFieldSpec(savedpost.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SavedPostDeleteOne is the builder for deleting a single SavedPost entity.
type SavedPostDeleteOne struct {
	_d *SavedPostDelete
}

// Where appends a list predicates to the SavedPostDelete builder.
func (_d *SavedPostDeleteOne) Where(ps ...predicate.SavedPost) *SavedPostDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SavedPostDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{savedpost.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SavedPostDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
