// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/post"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/profile"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/savedpost"
)

// SavedPostCreate is the builder for creating a SavedPost entity.
type SavedPostCreate struct {
	config
	mutation *SavedPostMutation
	hooks    []Hook
}

// SetPostID sets the "post_id" field.
func (_c *SavedPostCreate) SetPostID(v string) *SavedPostCreate {
	_c.mutation.SetPostID(v)
	return _c
}

// SetProfileID sets the "profile_id" field.
func (_c *SavedPostCreate) SetProfileID(v string) *SavedPostCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SavedPostCreate) SetCreatedAt(v time.Time) *SavedPostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SavedPostCreate) SetID(v string) *SavedPostCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetPost sets the "post" edge to the Post entity.
func (_c *SavedPostCreate) SetPost(v *Post) *SavedPostCreate {
	return _c.SetPostID(v.ID)
}

// SetProfile sets the "profile" edge to the Profile entity.
func (_c *SavedPostCreate) SetProfile(v *Profile) *SavedPostCreate {
	return _c.SetProfileID(v.ID)
}

// Mutation returns the SavedPostMutation object of the builder.
func (_c *SavedPostCreate) Mutation() *SavedPostMutation {
	return _c.mutation
}

// Save creates the SavedPost in the database.
func (_c *SavedPostCreate) Save(ctx context.Context) (*SavedPost, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SavedPostCreate) SaveX(ctx context.Context) *SavedPost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedPostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedPostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SavedPostCreate) check() error {
	if _, ok := _c.mutation.PostID(); !ok {
		return &ValidationError{Name: "post_id", err: errors.New(`ent: missing required field "SavedPost.post_id"`)}
	}
	if _, ok := _c.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "SavedPost.profile_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SavedPost.created_at"`)}
	}
	if len(_c.mutation.PostIDs()) == 0 {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "SavedPost.post"`)}
	}
	if len(_c.mutation.ProfileIDs()) == 0 {
		return &ValidationError{Name: "profile", err: errors.New(`ent: missing required edge "SavedPost.profile"`)}
	}
	return nil
}

func (_c *SavedPostCreate) sqlSave(ctx context.Context) (*SavedPost, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SavedPost.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SavedPostCreate) createSpec() (*SavedPost, *sqlgraph.CreateSpec) {
	var (
		_node = &SavedPost{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(savedpost.Table, sqlgraph.NewFieldSpec(savedpost.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(savedpost.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savedpost.PostTable,
			Columns: []string{savedpost.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   savedpost.ProfileTable,
			Columns: []string{savedpost.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProfileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SavedPostCreateBulk is the builder for creating many SavedPost entities in bulk.
type SavedPostCreateBulk struct {
	config
	err      error
	builders []*SavedPostCreate
}

// Save creates the SavedPost entities in the database.
func (_c *SavedPostCreateBulk) Save(ctx context.Context) ([]*SavedPost, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SavedPost, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SavedPostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SavedPostCreateBulk) SaveX(ctx context.Context) []*SavedPost {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SavedPostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SavedPostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
