// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/post"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/profile"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/savedpost"
)

// SavedPost is the model entity for the SavedPost schema.
type SavedPost struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// PostID holds the value of the "post_id" field.
	PostID string `json:"post_id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID string `json:"profile_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SavedPostQuery when eager-loading is set.
	Edges        SavedPostEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SavedPostEdges holds the relations/edges for other nodes in the graph.
type SavedPostEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// Profile holds the value of the profile edge.
	Profile *Profile `json:"profile,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SavedPostEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// ProfileOrErr returns the Profile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SavedPostEdges) ProfileOrErr() (*Profile, error) {
	if e.Profile != nil {
		return e.Profile, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: profile.Label}
	}
	return nil, &NotLoadedError{edge: "profile"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SavedPost) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case savedpost.FieldID, savedpost.FieldPostID, savedpost.FieldProfileID:
			values[i] = new(sql.NullString)
		case savedpost.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SavedPost fields.
func (_m *SavedPost) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case savedpost.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case savedpost.FieldPostID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field post_id", values[i])
			} else if value.Valid {
				_m.PostID = value.String
			}
		case savedpost.FieldProfileID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value.Valid {
				_m.ProfileID = value.String
			}
		case savedpost.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SavedPost.
// This includes values selected through modifiers, order, etc.
func (_m *SavedPost) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the SavedPost entity.
func (_m *SavedPost) QueryPost() *PostQuery {
	return NewSavedPostClient(_m.config).QueryPost(_m)
}

// QueryProfile queries the "profile" edge of the SavedPost entity.
func (_m *SavedPost) QueryProfile() *ProfileQuery {
	return NewSavedPostClient(_m.config).QueryProfile(_m)
}

// Update returns a builder for updating this SavedPost.
// Note that you need to call SavedPost.Unwrap() before calling this method if this SavedPost
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SavedPost) Update() *SavedPostUpdateOne {
	return NewSavedPostClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SavedPost entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SavedPost) Unwrap() *SavedPost {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SavedPost is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SavedPost) String() string {
	var builder strings.Builder
	builder.WriteString("SavedPost(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("post_id=")
	builder.WriteString(_m.PostID)
	builder.WriteString(", ")
	builder.WriteString("profile_id=")
	builder.WriteString(_m.ProfileID)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SavedPosts is a parsable slice of SavedPost.
type SavedPosts []*SavedPost
