// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/post"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/predicate"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/profile"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/savedpost"
)

// SavedPostQuery is the builder for querying SavedPost entities.
type SavedPostQuery struct {
	config
	ctx         *QueryContext
	order       []savedpost.OrderOption
	inters      []Interceptor
	predicates  []predicate.SavedPost
	withPost    *PostQuery
	withProfile *ProfileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SavedPostQuery builder.
func (_q *SavedPostQuery) Where(ps ...predicate.SavedPost) *SavedPostQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SavedPostQuery) Limit(limit int) *SavedPostQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SavedPostQuery) Offset(offset int) *SavedPostQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SavedPostQuery) Unique(unique bool) *SavedPostQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SavedPostQuery) Order(o ...savedpost.OrderOption) *SavedPostQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPost chains the current query on the "post" edge.
func (_q *SavedPostQuery) QueryPost() *PostQuery {
	query := (&PostClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(savedpost.Table, savedpost.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, savedpost.PostTable, savedpost.PostColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProfile chains the current query on the "profile" edge.
func (_q *SavedPostQuery) QueryProfile() *ProfileQuery {
	query := (&ProfileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(savedpost.Table, savedpost.FieldID, selector),
			sqlgraph.To(profile.Table, profile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, savedpost.ProfileTable, savedpost.ProfileColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SavedPost entity from the query.
// Returns a *NotFoundError when no SavedPost was found.
func (_q *SavedPostQuery) First(ctx context.Context) (*SavedPost, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{savedpost.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SavedPostQuery) FirstX(ctx context.Context) *SavedPost {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SavedPost ID from the query.
// Returns a *NotFoundError when no SavedPost ID was found.
func (_q *SavedPostQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{savedpost.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SavedPostQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SavedPost entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SavedPost entity is found.
// Returns a *NotFoundError when no SavedPost entities are found.
func (_q *SavedPostQuery) Only(ctx context.Context) (*SavedPost, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{savedpost.Label}
	default:
		return nil, &NotSingularError{savedpost.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SavedPostQuery) OnlyX(ctx context.Context) *SavedPost {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SavedPost ID in the query.
// Returns a *NotSingularError when more than one SavedPost ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SavedPostQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{savedpost.Label}
	default:
		err = &NotSingularError{savedpost.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SavedPostQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SavedPosts.
func (_q *SavedPostQuery) All(ctx context.Context) ([]*SavedPost, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SavedPost, *SavedPostQuery]()
	return withInterceptors[[]*SavedPost](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SavedPostQuery) AllX(ctx context.Context) []*SavedPost {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SavedPost IDs.
func (_q *SavedPostQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(savedpost.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SavedPostQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SavedPostQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SavedPostQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SavedPostQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SavedPostQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SavedPostQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SavedPostQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SavedPostQuery) Clone() *SavedPostQuery {
	if _q == nil {
		return nil
	}
	return &SavedPostQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]savedpost.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.SavedPost{}, _q.predicates...),
		withPost:    _q.withPost.Clone(),
		withProfile: _q.withProfile.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPost tells the query-builder to eager-load the nodes that are connected to
// the "post" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SavedPostQuery) WithPost(opts ...func(*PostQuery)) *SavedPostQuery {
	query := (&PostClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPost = query
	return _q
}

// WithProfile tells the query-builder to eager-load the nodes that are connected to
// the "profile" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SavedPostQuery) WithProfile(opts ...func(*ProfileQuery)) *SavedPostQuery {
	query := (&ProfileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProfile = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		PostID string `json:"post_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SavedPost.Query().
//		GroupBy(savedpost.FieldPostID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SavedPostQuery) GroupBy(field string, fields ...string) *SavedPostGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SavedPostGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = savedpost.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		PostID string `json:"post_id,omitempty"`
//	}
//
//	client.SavedPost.Query().
//		Select(savedpost.FieldPostID).
//		Scan(ctx, &v)
func (_q *SavedPostQuery) Select(fields ...string) *SavedPostSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SavedPostSelect{SavedPostQuery: _q}
	sbuild.label = savedpost.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SavedPostSelect configured with the given aggregations.
func (_q *SavedPostQuery) Aggregate(fns ...AggregateFunc) *SavedPostSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SavedPostQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !savedpost.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SavedPostQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SavedPost, error) {
	var (
		nodes       = []*SavedPost{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withPost != nil,
			_q.withProfile != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SavedPost).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SavedPost{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPost; query != nil {
		if err := _q.loadPost(ctx, query, nodes, nil,
			func(n *SavedPost, e *Post) { n.Edges.Post = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProfile; query != nil {
		if err := _q.loadProfile(ctx, query, nodes, nil,
			func(n *SavedPost, e *Profile) { n.Edges.Profile = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SavedPostQuery) loadPost(ctx context.Context, query *PostQuery, nodes []*SavedPost, init func(*SavedPost), assign func(*SavedPost, *Post)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*SavedPost)
	for i := range nodes {
		fk := nodes[i].PostID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(post.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "post_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *SavedPostQuery) loadProfile(ctx context.Context, query *ProfileQuery, nodes []*SavedPost, init func(*SavedPost), assign func(*SavedPost, *Profile)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*SavedPost)
	for i := range nodes {
		fk := nodes[i].ProfileID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(profile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "profile_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *SavedPostQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SavedPostQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(savedpost.Table, savedpost.Columns, sqlgraph.NewFieldSpec(savedpost.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, savedpost.FieldID)
		for i := range fields {
			if fields[i] != savedpost.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withPost != nil {
			_spec.Node.AddColumnOnce(savedpost.FieldPostID)
		}
		if _q.withProfile != nil {
			_spec.Node.AddColumnOnce(savedpost.FieldProfileID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SavedPostQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(savedpost.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = savedpost.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SavedPostGroupBy is the group-by builder for SavedPost entities.
type SavedPostGroupBy struct {
	selector
	build *SavedPostQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SavedPostGroupBy) Aggregate(fns ...AggregateFunc) *SavedPostGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SavedPostGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SavedPostQuery, *SavedPostGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SavedPostGroupBy) sqlScan(ctx context.Context, root *SavedPostQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SavedPostSelect is the builder for selecting fields of SavedPost entities.
type SavedPostSelect struct {
	*SavedPostQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SavedPostSelect) Aggregate(fns ...AggregateFunc) *SavedPostSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SavedPostSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SavedPostQuery, *SavedPostSelect](ctx, _s.SavedPostQuery, _s, _s.inters, v)
}

func (_s *SavedPostSelect) sqlScan(ctx context.Context, root *SavedPostQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
