// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "body", Type: field.TypeString, Size: 8800, SchemaType: map[string]string{"postgres": "varchar(8800)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "post_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "author_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comments_post_id_fkey",
				Columns:    []*schema.Column{CommentsColumns[4]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "comments_author_id_fkey",
				Columns:    []*schema.Column{CommentsColumns[5]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "comments_post_feed_idx",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[4], CommentsColumns[2], CommentsColumns[0]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						CommentsColumns[2].Name: true,

						CommentsColumns[0].Name: true,
					},
				},
			},
			{
				Name:    "comments_author_id_idx",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[5]},
			},
		},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "body", Type: field.TypeString, Size: 8800, SchemaType: map[string]string{"postgres": "varchar(8800)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "author_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "posts_author_id_fkey",
				Columns:    []*schema.Column{PostsColumns[4]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "posts_feed_idx",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[2], PostsColumns[0]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						PostsColumns[2].Name: true,

						PostsColumns[0].Name: true,
					},
				},
			},
			{
				Name:    "posts_author_id_idx",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[4]},
			},
		},
	}
	// PostLikesColumns holds the columns for the "post_likes" table.
	PostLikesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "post_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "profile_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// PostLikesTable holds the schema information for the "post_likes" table.
	PostLikesTable = &schema.Table{
		Name:       "post_likes",
		Columns:    PostLikesColumns,
		PrimaryKey: []*schema.Column{PostLikesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "post_likes_post_id_fkey",
				Columns:    []*schema.Column{PostLikesColumns[2]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "post_likes_profile_id_fkey",
				Columns:    []*schema.Column{PostLikesColumns[3]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "post_likes_post_profile_unique_idx",
				Unique:  true,
				Columns: []*schema.Column{PostLikesColumns[2], PostLikesColumns[3]},
			},
			{
				Name:    "post_likes_profile_idx",
				Unique:  false,
				Columns: []*schema.Column{PostLikesColumns[3], PostLikesColumns[1]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						PostLikesColumns[1].Name: true,
					},
				},
			},
		},
	}
	// PostMediaColumns holds the columns for the "post_media" table.
	PostMediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "object_key", Type: field.TypeString, Size: 512, SchemaType: map[string]string{"postgres": "varchar(512)"}},
		{Name: "public_url", Type: field.TypeString, Size: 2048, SchemaType: map[string]string{"postgres": "varchar(2048)"}},
		{Name: "alt_text", Type: field.TypeString, Size: 240, SchemaType: map[string]string{"postgres": "varchar(240)"}},
		{Name: "mime_type", Type: field.TypeString, Size: 64, SchemaType: map[string]string{"postgres": "varchar(64)"}},
		{Name: "width", Type: field.TypeInt, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "height", Type: field.TypeInt, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "post_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// PostMediaTable holds the schema information for the "post_media" table.
	PostMediaTable = &schema.Table{
		Name:       "post_media",
		Columns:    PostMediaColumns,
		PrimaryKey: []*schema.Column{PostMediaColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "post_media_post_id_fkey",
				Columns:    []*schema.Column{PostMediaColumns[8]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "post_media_post_id_idx",
				Unique:  true,
				Columns: []*schema.Column{PostMediaColumns[8]},
			},
		},
	}
	// ProfilesColumns holds the columns for the "profiles" table.
	ProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "clerk_subject", Type: field.TypeString, Unique: true, Size: 256, SchemaType: map[string]string{"postgres": "varchar(256)"}},
		{Name: "display_name", Type: field.TypeString, Size: 80, SchemaType: map[string]string{"postgres": "varchar(80)"}},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true, Size: 2048, SchemaType: map[string]string{"postgres": "varchar(2048)"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ProfilesTable holds the schema information for the "profiles" table.
	ProfilesTable = &schema.Table{
		Name:       "profiles",
		Columns:    ProfilesColumns,
		PrimaryKey: []*schema.Column{ProfilesColumns[0]},
	}
	// SavedPostsColumns holds the columns for the "saved_posts" table.
	SavedPostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "post_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
		{Name: "profile_id", Type: field.TypeString, SchemaType: map[string]string{"postgres": "uuid"}},
	}
	// SavedPostsTable holds the schema information for the "saved_posts" table.
	SavedPostsTable = &schema.Table{
		Name:       "saved_posts",
		Columns:    SavedPostsColumns,
		PrimaryKey: []*schema.Column{SavedPostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "saved_posts_post_id_fkey",
				Columns:    []*schema.Column{SavedPostsColumns[2]},
				RefColumns: []*schema.Column{PostsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "saved_posts_profile_id_fkey",
				Columns:    []*schema.Column{SavedPostsColumns[3]},
				RefColumns: []*schema.Column{ProfilesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "saved_posts_post_profile_unique_idx",
				Unique:  true,
				Columns: []*schema.Column{SavedPostsColumns[2], SavedPostsColumns[3]},
			},
			{
				Name:    "saved_posts_private_feed_idx",
				Unique:  false,
				Columns: []*schema.Column{SavedPostsColumns[3], SavedPostsColumns[1], SavedPostsColumns[0]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						SavedPostsColumns[1].Name: true,

						SavedPostsColumns[0].Name: true,
					},
				},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommentsTable,
		PostsTable,
		PostLikesTable,
		PostMediaTable,
		ProfilesTable,
		SavedPostsTable,
	}
)

func init() {
	CommentsTable.ForeignKeys[0].RefTable = PostsTable
	CommentsTable.ForeignKeys[1].RefTable = ProfilesTable
	CommentsTable.Annotation = &entsql.Annotation{}
	CommentsTable.Annotation.Checks = map[string]string{
		"comments_body_nonempty": "length(btrim(body)) > 0",
		"comments_timestamps":    "updated_at >= created_at",
	}
	PostsTable.ForeignKeys[0].RefTable = ProfilesTable
	PostsTable.Annotation = &entsql.Annotation{}
	PostsTable.Annotation.Checks = map[string]string{
		"posts_body_nonempty": "length(btrim(body)) > 0",
		"posts_timestamps":    "updated_at >= created_at",
	}
	PostLikesTable.ForeignKeys[0].RefTable = PostsTable
	PostLikesTable.ForeignKeys[1].RefTable = ProfilesTable
	PostMediaTable.ForeignKeys[0].RefTable = PostsTable
	PostMediaTable.Annotation = &entsql.Annotation{}
	PostMediaTable.Annotation.Checks = map[string]string{
		"post_media_height_positive": "height > 0",
		"post_media_width_positive":  "width > 0",
	}
	ProfilesTable.Annotation = &entsql.Annotation{}
	ProfilesTable.Annotation.Checks = map[string]string{
		"profiles_timestamps": "updated_at >= created_at",
	}
	SavedPostsTable.ForeignKeys[0].RefTable = PostsTable
	SavedPostsTable.ForeignKeys[1].RefTable = ProfilesTable
}
