// Code generated by ent, DO NOT EDIT.

package postmedia

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SourceSenseiTheRealOne/coach-connect/mvp-v2/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldContainsFold(FieldID, id))
}

// PostID applies equality check predicate on the "post_id" field. It's identical to PostIDEQ.
func PostID(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldPostID, v))
}

// ObjectKey applies equality check predicate on the "object_key" field. It's identical to ObjectKeyEQ.
func ObjectKey(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldObjectKey, v))
}

// PublicURL applies equality check predicate on the "public_url" field. It's identical to PublicURLEQ.
func PublicURL(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldPublicURL, v))
}

// AltText applies equality check predicate on the "alt_text" field. It's identical to AltTextEQ.
func AltText(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldAltText, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldMimeType, v))
}

// Width applies equality check predicate on the "width" field. It's identical to WidthEQ.
func Width(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldWidth, v))
}

// Height applies equality check predicate on the "height" field. It's identical to HeightEQ.
func Height(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldHeight, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldCreatedAt, v))
}

// PostIDEQ applies the EQ predicate on the "post_id" field.
func PostIDEQ(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldPostID, v))
}

// PostIDNEQ applies the NEQ predicate on the "post_id" field.
func PostIDNEQ(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldPostID, v))
}

// PostIDIn applies the In predicate on the "post_id" field.
func PostIDIn(vs ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldPostID, vs...))
}

// PostIDNotIn applies the NotIn predicate on the "post_id" field.
func PostIDNotIn(vs ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldPostID, vs...))
}

// PostIDGT applies the GT predicate on the "post_id" field.
func PostIDGT(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldPostID, v))
}

// PostIDGTE applies the GTE predicate on the "post_id" field.
func PostIDGTE(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldPostID, v))
}

// PostIDLT applies the LT predicate on the "post_id" field.
func PostIDLT(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldPostID, v))
}

// PostIDLTE applies the LTE predicate on the "post_id" field.
func PostIDLTE(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldPostID, v))
}

// PostIDContains applies the Contains predicate on the "post_id" field.
func PostIDContains(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldContains(FieldPostID, v))
}

// PostIDHasPrefix applies the HasPrefix predicate on the "post_id" field.
func PostIDHasPrefix(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldHasPrefix(FieldPostID, v))
}

// PostIDHasSuffix applies the HasSuffix predicate on the "post_id" field.
func PostIDHasSuffix(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldHasSuffix(FieldPostID, v))
}

// PostIDEqualFold applies the EqualFold predicate on the "post_id" field.
func PostIDEqualFold(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEqualFold(FieldPostID, v))
}

// PostIDContainsFold applies the ContainsFold predicate on the "post_id" field.
func PostIDContainsFold(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldContainsFold(FieldPostID, v))
}

// ObjectKeyEQ applies the EQ predicate on the "object_key" field.
func ObjectKeyEQ(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldObjectKey, v))
}

// ObjectKeyNEQ applies the NEQ predicate on the "object_key" field.
func ObjectKeyNEQ(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldObjectKey, v))
}

// ObjectKeyIn applies the In predicate on the "object_key" field.
func ObjectKeyIn(vs ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldObjectKey, vs...))
}

// ObjectKeyNotIn applies the NotIn predicate on the "object_key" field.
func ObjectKeyNotIn(vs ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldObjectKey, vs...))
}

// ObjectKeyGT applies the GT predicate on the "object_key" field.
func ObjectKeyGT(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldObjectKey, v))
}

// ObjectKeyGTE applies the GTE predicate on the "object_key" field.
func ObjectKeyGTE(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldObjectKey, v))
}

// ObjectKeyLT applies the LT predicate on the "object_key" field.
func ObjectKeyLT(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldObjectKey, v))
}

// ObjectKeyLTE applies the LTE predicate on the "object_key" field.
func ObjectKeyLTE(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldObjectKey, v))
}

// ObjectKeyContains applies the Contains predicate on the "object_key" field.
func ObjectKeyContains(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldContains(FieldObjectKey, v))
}

// ObjectKeyHasPrefix applies the HasPrefix predicate on the "object_key" field.
func ObjectKeyHasPrefix(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldHasPrefix(FieldObjectKey, v))
}

// ObjectKeyHasSuffix applies the HasSuffix predicate on the "object_key" field.
func ObjectKeyHasSuffix(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldHasSuffix(FieldObjectKey, v))
}

// ObjectKeyEqualFold applies the EqualFold predicate on the "object_key" field.
func ObjectKeyEqualFold(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEqualFold(FieldObjectKey, v))
}

// ObjectKeyContainsFold applies the ContainsFold predicate on the "object_key" field.
func ObjectKeyContainsFold(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldContainsFold(FieldObjectKey, v))
}

// PublicURLEQ applies the EQ predicate on the "public_url" field.
func PublicURLEQ(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldPublicURL, v))
}

// PublicURLNEQ applies the NEQ predicate on the "public_url" field.
func PublicURLNEQ(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldPublicURL, v))
}

// PublicURLIn applies the In predicate on the "public_url" field.
func PublicURLIn(vs ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldPublicURL, vs...))
}

// PublicURLNotIn applies the NotIn predicate on the "public_url" field.
func PublicURLNotIn(vs ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldPublicURL, vs...))
}

// PublicURLGT applies the GT predicate on the "public_url" field.
func PublicURLGT(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldPublicURL, v))
}

// PublicURLGTE applies the GTE predicate on the "public_url" field.
func PublicURLGTE(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldPublicURL, v))
}

// PublicURLLT applies the LT predicate on the "public_url" field.
func PublicURLLT(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldPublicURL, v))
}

// PublicURLLTE applies the LTE predicate on the "public_url" field.
func PublicURLLTE(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldPublicURL, v))
}

// PublicURLContains applies the Contains predicate on the "public_url" field.
func PublicURLContains(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldContains(FieldPublicURL, v))
}

// PublicURLHasPrefix applies the HasPrefix predicate on the "public_url" field.
func PublicURLHasPrefix(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldHasPrefix(FieldPublicURL, v))
}

// PublicURLHasSuffix applies the HasSuffix predicate on the "public_url" field.
func PublicURLHasSuffix(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldHasSuffix(FieldPublicURL, v))
}

// PublicURLEqualFold applies the EqualFold predicate on the "public_url" field.
func PublicURLEqualFold(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEqualFold(FieldPublicURL, v))
}

// PublicURLContainsFold applies the ContainsFold predicate on the "public_url" field.
func PublicURLContainsFold(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldContainsFold(FieldPublicURL, v))
}

// AltTextEQ applies the EQ predicate on the "alt_text" field.
func AltTextEQ(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldAltText, v))
}

// AltTextNEQ applies the NEQ predicate on the "alt_text" field.
func AltTextNEQ(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldAltText, v))
}

// AltTextIn applies the In predicate on the "alt_text" field.
func AltTextIn(vs ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldAltText, vs...))
}

// AltTextNotIn applies the NotIn predicate on the "alt_text" field.
func AltTextNotIn(vs ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldAltText, vs...))
}

// AltTextGT applies the GT predicate on the "alt_text" field.
func AltTextGT(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldAltText, v))
}

// AltTextGTE applies the GTE predicate on the "alt_text" field.
func AltTextGTE(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldAltText, v))
}

// AltTextLT applies the LT predicate on the "alt_text" field.
func AltTextLT(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldAltText, v))
}

// AltTextLTE applies the LTE predicate on the "alt_text" field.
func AltTextLTE(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldAltText, v))
}

// AltTextContains applies the Contains predicate on the "alt_text" field.
func AltTextContains(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldContains(FieldAltText, v))
}

// AltTextHasPrefix applies the HasPrefix predicate on the "alt_text" field.
func AltTextHasPrefix(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldHasPrefix(FieldAltText, v))
}

// AltTextHasSuffix applies the HasSuffix predicate on the "alt_text" field.
func AltTextHasSuffix(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldHasSuffix(FieldAltText, v))
}

// AltTextEqualFold applies the EqualFold predicate on the "alt_text" field.
func AltTextEqualFold(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEqualFold(FieldAltText, v))
}

// AltTextContainsFold applies the ContainsFold predicate on the "alt_text" field.
func AltTextContainsFold(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldContainsFold(FieldAltText, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldContainsFold(FieldMimeType, v))
}

// WidthEQ applies the EQ predicate on the "width" field.
func WidthEQ(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldWidth, v))
}

// WidthNEQ applies the NEQ predicate on the "width" field.
func WidthNEQ(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldWidth, v))
}

// WidthIn applies the In predicate on the "width" field.
func WidthIn(vs ...int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldWidth, vs...))
}

// WidthNotIn applies the NotIn predicate on the "width" field.
func WidthNotIn(vs ...int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldWidth, vs...))
}

// WidthGT applies the GT predicate on the "width" field.
func WidthGT(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldWidth, v))
}

// WidthGTE applies the GTE predicate on the "width" field.
func WidthGTE(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldWidth, v))
}

// WidthLT applies the LT predicate on the "width" field.
func WidthLT(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldWidth, v))
}

// WidthLTE applies the LTE predicate on the "width" field.
func WidthLTE(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldWidth, v))
}

// HeightEQ applies the EQ predicate on the "height" field.
func HeightEQ(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldHeight, v))
}

// HeightNEQ applies the NEQ predicate on the "height" field.
func HeightNEQ(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldHeight, v))
}

// HeightIn applies the In predicate on the "height" field.
func HeightIn(vs ...int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldHeight, vs...))
}

// HeightNotIn applies the NotIn predicate on the "height" field.
func HeightNotIn(vs ...int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldHeight, vs...))
}

// HeightGT applies the GT predicate on the "height" field.
func HeightGT(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldHeight, v))
}

// HeightGTE applies the GTE predicate on the "height" field.
func HeightGTE(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldHeight, v))
}

// HeightLT applies the LT predicate on the "height" field.
func HeightLT(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldHeight, v))
}

// HeightLTE applies the LTE predicate on the "height" field.
func HeightLTE(v int) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldHeight, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PostMedia {
	return predicate.PostMedia(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPost applies the HasEdge predicate on the "post" edge.
func HasPost() predicate.PostMedia {
	return predicate.PostMedia(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PostTable, PostColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPostWith applies the HasEdge predicate on the "post" edge with a given conditions (other predicates).
func HasPostWith(preds ...predicate.Post) predicate.PostMedia {
	return predicate.PostMedia(func(s *sql.Selector) {
		step := newPostStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PostMedia) predicate.PostMedia {
	return predicate.PostMedia(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PostMedia) predicate.PostMedia {
	return predicate.PostMedia(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PostMedia) predicate.PostMedia {
	return predicate.PostMedia(sql.NotPredicates(p))
}
